project:
  type: website
  output-dir: docs

website:
  title: "Luciano Lu - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Public Policy Analytics
        menu:
          - href: assignments/assignment_1/assignment1_template.qmd
            text: "Census Data Quality for Policy Decisions"
          - href: assignments/assignment_2/Luciano_Lu_assignment2.qmd
            text: "Spatial Analysis and Visualization - Healthcare Access and Equity in Pennsylvania"
          - href: assignments/midterm/appendix_nolog.qmd
            text: "Philadelphia Housing Price Prediction Model"
          - href: assignments/assignment_4/Luciano_Lu_assignment4.qmd
            text: "Spatial Predictive Modeling â€“ Sanitation 311 Requests"
          - href: assignments/assignment_5/hw_5.qmd
            text: "Space-Time Prediction of Bike Share Demand: Philadelphia Indego"
          - href: assignments/Final/FINAL_1.qmd
            text: "Fire Alarms Analysis"
      - text: PPT
        menu:
          - href: assignments/midterm/Presentation_slides.qmd
            text: "Midterm PPT"
          - href: assignments/Final/presentation/Final_Presentation.qmd
            text: "Final PPT"
          
            
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto

